// review-app/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  interface TestResult {
    testIdx: number;
    prompt: { label: string };
    provider: { label: string };
    testCase: { vars: Record<string, string> };
    response: { output: string };
    gradingResult: { pass: boolean; score: number; reason: string };
    latencyMs: number;
  }

  interface Annotation {
    rating: number;
    notes: string;
  }

  interface AnnotationsData {
    [evalId: string]: {
      [testIdx: string]: {
        [promptLabel: string]: {
          [providerLabel: string]: Annotation;
        };
      };
    };
  }

  let results: TestResult[] = [];
  let allResults: TestResult[] = [];
  let annotations: AnnotationsData = {};
  let evalId = '';
  let selectedPrompt = '';
  let selectedProvider = '';
  let currentTestIdx = 0;
  let loading = true;
  let error = '';

  let rating = 0;
  let notes = '';
  let notesTextarea: HTMLTextAreaElement;

  onMount(async () => {
    try {
      const [resultsRes, annotationsRes] = await Promise.all([
        fetch('/api/results'),
        fetch('/api/annotations'),
      ]);

      if (!resultsRes.ok) throw new Error('Failed to load results');
      if (!annotationsRes.ok) throw new Error('Failed to load annotations');

      const resultsData = await resultsRes.json();
      const annotationsData = await annotationsRes.json();

      allResults = resultsData.results || [];
      annotations = annotationsData;
      evalId = resultsData.evalId || '';

      // Get unique prompts and providers
      const uniquePrompts = new Set<string>();
      const uniqueProviders = new Set<string>();

      allResults.forEach((r) => {
        uniquePrompts.add(r.prompt?.label || 'unknown');
        uniqueProviders.add(r.provider?.label || 'unknown');
      });

      selectedPrompt = Array.from(uniquePrompts)[0] || '';
      selectedProvider = Array.from(uniqueProviders)[0] || '';

      filterResults();
      loading = false;
    } catch (e) {
      error = String(e);
      loading = false;
    }
  });

  function filterResults() {
    results = allResults.filter(
      (r) =>
        r.prompt?.label === selectedPrompt &&
        r.provider?.label === selectedProvider
    );
    currentTestIdx = 0;
    loadCurrentResult();
  }

  function loadCurrentResult() {
    if (results.length === 0) return;

    const result = results[currentTestIdx];
    const testIdx = result.testIdx;

    const annotation = annotations[evalId]?.[testIdx]?.[selectedPrompt]?.[
      selectedProvider
    ] || { rating: 0, notes: '' };

    rating = annotation.rating || 0;
    notes = annotation.notes || '';
  }

  function truncate(text: string, maxLength = 150): string {
    if (!text) return '';
    return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
  }

  function getUniquePrompts(): string[] {
    const unique = new Set<string>();
    allResults.forEach((r) => unique.add(r.prompt?.label || 'unknown'));
    return Array.from(unique).sort();
  }

  function getUniqueProviders(): string[] {
    const unique = new Set<string>();
    allResults.forEach((r) => unique.add(r.provider?.label || 'unknown'));
    return Array.from(unique).sort();
  }

  function setRating(newRating: number) {
    rating = newRating;
  }

  async function saveAndNext() {
    const result = results[currentTestIdx];
    const testIdx = result.testIdx;

    if (!annotations[evalId]) annotations[evalId] = {};
    if (!annotations[evalId][testIdx]) annotations[evalId][testIdx] = {};
    if (!annotations[evalId][testIdx][selectedPrompt]) {
      annotations[evalId][testIdx][selectedPrompt] = {};
    }

    annotations[evalId][testIdx][selectedPrompt][selectedProvider] = {
      rating,
      notes,
    };

    try {
      const res = await fetch('/api/annotations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(annotations),
      });

      if (!res.ok) throw new Error('Failed to save');

      if (currentTestIdx < results.length - 1) {
        currentTestIdx++;
        loadCurrentResult();
      }
    } catch (e) {
      error = String(e);
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    // Skip if we're typing in the textarea
    if (document.activeElement === notesTextarea) {
      // Cmd+Enter to save
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        saveAndNext();
      }
      return;
    }

    // 0-5 to set rating
    if (/^[0-5]$/.test(e.key)) {
      setRating(parseInt(e.key, 10));
      return;
    }

    // Enter to focus notes
    if (e.key === 'Enter') {
      e.preventDefault();
      notesTextarea?.focus();
    }
  }

  const ratedCount = results.filter((r) => {
    const annotation =
      annotations[evalId]?.[r.testIdx]?.[selectedPrompt]?.[selectedProvider] ||
      {};
    return (annotation.rating || 0) > 0;
  }).length;

  const allRatings = results.map((r) => {
    const annotation =
      annotations[evalId]?.[r.testIdx]?.[selectedPrompt]?.[selectedProvider] ||
      {};
    return annotation.rating || 0;
  });

  const avgRating =
    allRatings.filter((r) => r > 0).length > 0
      ? allRatings.reduce((a, b) => a + b, 0) /
        allRatings.filter((r) => r > 0).length
      : 0;

  const ratingsMap = {
    0: '⏳ Not rated',
    1: '❌ Poor',
    2: '⚠️ Needs improvement',
    3: '✓ Acceptable',
    4: '✓✓ Good',
    5: '✓✓✓ Excellent',
  };

  $: if (results.length > 0) {
    loadCurrentResult();
  }
</script>

<svelte:window on:keydown={handleKeyDown} />

<style>
  :global(body) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
      'Helvetica Neue', Arial, sans-serif;
    background: #f5f5f5;
    margin: 0;
    padding: 0;
  }

  .container {
    display: grid;
    grid-template-columns: 300px 1fr;
    gap: 0;
    height: 100vh;
  }

  .sidebar {
    background: #fff;
    border-right: 1px solid #e0e0e0;
    padding: 24px;
    overflow-y: auto;
  }

  .main {
    display: flex;
    flex-direction: column;
    padding: 24px;
    overflow: hidden;
  }

  .content-wrapper {
    display: grid;
    grid-template-columns: 1fr 350px;
    gap: 24px;
    flex: 1;
    overflow: hidden;
    margin-bottom: 24px;
  }

  .left-panel {
    display: flex;
    flex-direction: column;
    gap: 12px;
    overflow: hidden;
  }

  .header {
    font-size: 20px;
    font-weight: 600;
    margin: 0 0 16px 0;
  }

  .section-header {
    font-size: 14px;
    font-weight: 600;
    text-transform: uppercase;
    color: #666;
    margin: 16px 0 12px 0;
    border-bottom: 1px solid #e0e0e0;
    padding-bottom: 8px;
  }

  .select-group {
    margin-bottom: 16px;
  }

  label {
    display: block;
    font-size: 12px;
    font-weight: 500;
    margin-bottom: 6px;
    color: #333;
  }

  select {
    width: 100%;
    padding: 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
  }

  .navigation {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    margin: 16px 0;
  }

  button {
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: #fff;
    cursor: pointer;
    font-size: 13px;
    transition: all 0.2s;
  }

  button:hover {
    background: #f0f0f0;
    border-color: #999;
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .metric {
    margin: 8px 0;
    font-size: 13px;
    color: #666;
  }

  .metric-value {
    font-weight: 600;
    color: #333;
  }

  .title {
    font-size: 24px;
    font-weight: 600;
    margin: 0 0 4px 0;
  }

  .caption {
    font-size: 13px;
    color: #999;
    margin-bottom: 12px;
  }

  .question {
    background: #f9f9f9;
    padding: 12px;
    border-radius: 4px;
    margin-bottom: 12px;
    font-size: 13px;
    line-height: 1.5;
    border-left: 3px solid #2196f3;
    flex-shrink: 0;
  }

  .response {
    background: #fff;
    padding: 16px;
    border-radius: 4px;
    margin-bottom: 12px;
    font-size: 14px;
    line-height: 1.6;
    border: 1px solid #e0e0e0;
    overflow-y: auto;
    flex: 1;
  }

  .metrics-section {
    background: #f9f9f9;
    padding: 12px;
    border-radius: 4px;
    font-size: 12px;
    flex-shrink: 0;
  }

  .metrics-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
    margin: 8px 0;
  }

  .metric-item {
    background: #fff;
    padding: 8px;
    border-radius: 3px;
    border: 1px solid #e0e0e0;
    text-align: center;
  }

  .rating-section {
    background: #fff;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
    padding: 16px;
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  .subheader {
    font-size: 16px;
    font-weight: 600;
    margin: 0 0 12px 0;
  }

  .rating-control {
    margin-bottom: 16px;
    flex-shrink: 0;
  }

  .rating-label {
    font-size: 14px;
    font-weight: 500;
    margin-bottom: 8px;
  }

  .rating-slider {
    width: 100%;
    height: 6px;
    border-radius: 3px;
    background: #ddd;
    outline: none;
    -webkit-appearance: none;
  }

  .rating-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: #2196f3;
    cursor: pointer;
  }

  .rating-slider::-moz-range-thumb {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: #2196f3;
    cursor: pointer;
    border: none;
  }

  .rating-display {
    font-size: 14px;
    font-weight: 600;
    color: #333;
    margin-top: 8px;
  }

  .notes-section {
    margin-top: 16px;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .notes-label {
    font-size: 14px;
    font-weight: 500;
    margin-bottom: 8px;
    flex-shrink: 0;
  }

  textarea {
    flex: 1;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
      'Helvetica Neue', Arial, sans-serif;
    font-size: 13px;
    resize: none;
    min-height: 0;
  }

  .button-group {
    display: grid;
    grid-template-columns: 1fr;
    gap: 8px;
    margin-top: 16px;
    flex-shrink: 0;
  }

  .save-button {
    background: #2196f3;
    color: white;
    border: none;
    padding: 10px;
    font-weight: 500;
    width: 100%;
  }

  .save-button:hover {
    background: #1976d2;
  }

  .loading,
  .error-message {
    padding: 24px;
    text-align: center;
  }

  .error-message {
    color: #d32f2f;
  }

  .stats-section {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    flex-shrink: 0;
    border-top: 1px solid #e0e0e0;
    padding-top: 16px;
  }

  .stat-item {
    background: #fff;
    padding: 12px;
    border-radius: 4px;
    border: 1px solid #e0e0e0;
    text-align: center;
  }

  .stat-label {
    font-size: 11px;
    color: #999;
    text-transform: uppercase;
    font-weight: 500;
  }

  .stat-value {
    font-size: 20px;
    font-weight: 600;
    margin-top: 6px;
  }

  .keyboard-hint {
    font-size: 11px;
    color: #999;
    margin-top: 8px;
    font-style: italic;
  }

  input[type='range'] {
    cursor: pointer;
  }
</style>

{#if loading}
  <div class="loading">Loading...</div>
{:else if error}
  <div class="error-message">Error: {error}</div>
{:else if results.length === 0}
  <div class="error-message">No results found for this combination</div>
{:else}
  <div class="container">
    <div class="sidebar">
      <h2 class="header">🎯 Filters</h2>

      <div class="select-group">
        <label for="prompt-select">Prompt:</label>
        <select
          id="prompt-select"
          bind:value={selectedPrompt}
          on:change={filterResults}
        >
          {#each getUniquePrompts() as p}
            <option value={p}>{p}</option>
          {/each}
        </select>
      </div>

      <div class="select-group">
        <label for="provider-select">Model:</label>
        <select
          id="provider-select"
          bind:value={selectedProvider}
          on:change={filterResults}
        >
          {#each getUniqueProviders() as pr}
            <option value={pr}>{pr}</option>
          {/each}
        </select>
      </div>

      <div class="section-header">📍 Navigation</div>

      <div class="metric">
        <div class="metric-value">Progress</div>
        <div>{ratedCount}/{results.length} rated</div>
      </div>

      <div class="navigation">
        <button
          disabled={currentTestIdx === 0}
          on:click={() => {
            currentTestIdx--;
          }}
        >
          ← Previous
        </button>
        <button
          disabled={currentTestIdx === results.length - 1}
          on:click={() => {
            currentTestIdx++;
          }}
        >
          Next →
        </button>
      </div>

      {#if results.length > 0}
        <div class="select-group">
          <label for="jump-select">Jump to item:</label>
          <select
            id="jump-select"
            bind:value={currentTestIdx}
            on:change={() => {
              currentTestIdx = parseInt(currentTestIdx);
            }}
          >
            {#each results as result, idx}
              <option value={idx}>
                #{idx + 1} - {truncate(
                  result.testCase?.vars?.prompt || 'Q',
                  40
                )}
              </option>
            {/each}
          </select>
        </div>
      {/if}

      <div class="section-header">📊 Keyboard Shortcuts</div>
      <div class="keyboard-hint">
        <strong>0-5</strong>: Set rating<br />
        <strong>Enter</strong>: Focus notes<br />
        <strong>Cmd+Enter</strong>: Save & next
      </div>
    </div>

    <div class="main">
      {#if results.length > 0}
        <div>
          <div class="title">Review Results</div>
          <div class="caption">
            Test {currentTestIdx + 1} of {results.length}
          </div>
        </div>

        <div class="content-wrapper">
          <div class="left-panel">
            <div class="question">
              <strong>Question:</strong><br />
              {truncate(results[currentTestIdx].testCase?.vars?.prompt, 300)}
            </div>

            <div class="response">
              <strong>Model Response:</strong><br />
              {results[currentTestIdx].response?.output || 'No output'}
            </div>

            <div class="metrics-section">
              <strong>📊 Evaluation Metrics</strong>
              <div class="metrics-row">
                <div class="metric-item">
                  <div class="stat-label">Status</div>
                  <div class="stat-value">
                    {results[currentTestIdx].gradingResult?.pass ? '✓' : '✗'}
                  </div>
                </div>
                <div class="metric-item">
                  <div class="stat-label">Score</div>
                  <div class="stat-value">
                    {results[currentTestIdx].gradingResult?.score || 0}
                  </div>
                </div>
                <div class="metric-item">
                  <div class="stat-label">Latency</div>
                  <div class="stat-value">
                    {results[currentTestIdx].latencyMs}ms
                  </div>
                </div>
              </div>
              {#if results[currentTestIdx].gradingResult?.reason}
                <div style="margin-top: 8px; font-size: 12px;">
                  <strong>Reason:</strong> {results[currentTestIdx].gradingResult
                    ?.reason}
                </div>
              {/if}
            </div>
          </div>

          <div class="rating-section">
            <div class="subheader">⭐ Your Evaluation</div>

            <div class="rating-control">
              <label for="rating-slider" class="rating-label">
                Rating:
              </label>
              <input
                id="rating-slider"
                type="range"
                class="rating-slider"
                min="0"
                max="5"
                bind:value={rating}
                on:change={() => {
                  rating = parseInt(rating);
                }}
              />
              <div class="rating-display">
                {ratingsMap[rating]}
              </div>
            </div>

            <div class="notes-section">
              <label for="notes-textarea" class="notes-label">Notes:</label>
              <textarea
                id="notes-textarea"
                bind:value={notes}
                bind:this={notesTextarea}
                placeholder="Add comments or observations..."
              />
            </div>

            <div class="button-group">
              <button class="save-button" on:click={saveAndNext}>
                💾 Save & Continue
              </button>
            </div>
          </div>
        </div>

        <div class="stats-section">
          <div class="stat-item">
            <div class="stat-label">Rated</div>
            <div class="stat-value">{ratedCount}/{results.length}</div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Avg Rating</div>
            <div class="stat-value">
              {avgRating > 0 ? avgRating.toFixed(1) : 'N/A'}
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Excellent (5)</div>
            <div class="stat-value">
              {allRatings.filter((r) => r === 5).length}
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Poor (1)</div>
            <div class="stat-value">
              {allRatings.filter((r) => r === 1).length}
            </div>
          </div>
        </div>
      {/if}
    </div>
  </div>
{/if}

// review-app-shadcn/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import {
  loadPromptfooResults,
  loadAnnotations,
  saveAnnotations,
  getAnnotation,
  setAnnotation,
  truncateText,
  exportAnnotationsToJSON,
  exportToCSV,
} from './utils';
import type { PromptfooResult, AnnotationsStore } from './types';

function App() {
  const [data, setData] = useState<PromptfooResult | null>(null);
  const [annotations, setAnnotations] = useState<AnnotationsStore>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [selectedPrompt, setSelectedPrompt] = useState<string | null>(null);
  const [selectedProvider, setSelectedProvider] = useState<string | null>(null);
  const [currentTestIdx, setCurrentTestIdx] = useState(0);
  const [localNotes, setLocalNotes] = useState('');

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    const loadData = async () => {
      try {
        const promptfooData = await loadPromptfooResults();
        if (!promptfooData) {
          setError('No evaluation results found. Run promptfoo first.');
          setLoading(false);
          return;
        }

        setData(promptfooData);

        const annots = await loadAnnotations();
        setAnnotations(annots);

        const prompts = Array.from(
          new Set(
            promptfooData.results.results.map((r) => r.prompt?.label || 'unknown')
          )
        ).sort();
        const providers = Array.from(
          new Set(
            promptfooData.results.results.map((r) => r.provider?.label || 'unknown')
          )
        ).sort();

        if (prompts.length > 0) setSelectedPrompt(prompts[0]);
        if (providers.length > 0) setSelectedProvider(providers[0]);
      } catch (err) {
        setError(`Failed to load data: ${err}`);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  const prompts = data
    ? Array.from(
        new Set(data.results.results.map((r) => r.prompt?.label || 'unknown'))
      ).sort()
    : [];
  const providers = data
    ? Array.from(
        new Set(data.results.results.map((r) => r.provider?.label || 'unknown'))
      ).sort()
    : [];

  const filteredResults =
    data && selectedPrompt && selectedProvider
      ? data.results.results.filter(
          (r) =>
            r.prompt?.label === selectedPrompt &&
            r.provider?.label === selectedProvider
        )
      : [];

  const currentResult = filteredResults[currentTestIdx];

  const currentAnnotation = currentResult
    ? getAnnotation(
        annotations,
        data!.evalId,
        currentResult.testIdx,
        selectedPrompt!,
        selectedProvider!
      )
    : { rating: 0, notes: '' };

  useEffect(() => {
    setLocalNotes(currentAnnotation.notes);
  }, [currentAnnotation.notes, currentTestIdx]);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const targetElement = event.target as HTMLElement;

      if (event.key >= '0' && event.key <= '5') {
        if (
          targetElement.tagName !== 'INPUT' &&
          targetElement.tagName !== 'TEXTAREA'
        ) {
          event.preventDefault();
          const newRating = parseInt(event.key);
          handleSaveRating(newRating, currentAnnotation.notes);
        }
      }

      if (event.key === 'Enter' && !event.metaKey && !event.ctrlKey) {
        if (
          targetElement.tagName !== 'TEXTAREA' &&
          targetElement.tagName !== 'INPUT'
        ) {
          event.preventDefault();
          textareaRef.current?.focus();
        }
      }

      if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
        if (targetElement.tagName === 'TEXTAREA') {
          event.preventDefault();
          handleSaveAndNext();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentAnnotation, currentResult, selectedPrompt, selectedProvider, currentTestIdx, filteredResults, data, annotations]);

  const handleSaveRating = (rating: number, notes: string) => {
    if (!currentResult || !selectedPrompt || !selectedProvider) return;

    const updated = setAnnotation(
      annotations,
      data!.evalId,
      currentResult.testIdx,
      selectedPrompt,
      selectedProvider,
      rating,
      notes
    );
    setAnnotations(updated);
    saveAnnotations(updated);
  };

  const handleSaveAndNext = () => {
    if (!currentResult || !selectedPrompt || !selectedProvider) return;

    handleSaveRating(currentAnnotation.rating, localNotes);

    if (currentTestIdx < filteredResults.length - 1) {
      setCurrentTestIdx(currentTestIdx + 1);
    }
  };

  const ratingLabels: Record<number, string> = {
    0: '⏳ Not rated',
    1: '❌ Poor',
    2: '⚠️ Needs improvement',
    3: '✓ Acceptable',
    4: '✓✓ Good',
    5: '✓✓✓ Excellent',
  };

  const allRatings = filteredResults.map((r) =>
    getAnnotation(
      annotations,
      data!.evalId,
      r.testIdx,
      selectedPrompt!,
      selectedProvider!
    ).rating
  );
  const ratedItems = allRatings.filter((r) => r > 0).length;
  const avgRating = ratedItems > 0 ? allRatings.reduce((a, b) => a + b, 0) / ratedItems : 0;

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen p-4">
        <Alert variant="destructive" className="max-w-md">
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      </div>
    );
  }

  if (!currentResult || !data) {
    return (
      <div className="flex items-center justify-center min-h-screen p-4">
        <Alert className="max-w-md">
          <AlertTitle>No Results</AlertTitle>
          <AlertDescription>No results found for this combination</AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen">
      {/* Sidebar */}
      <div className="w-90 border-r bg-card p-6 flex flex-col gap-6 overflow-y-auto overflow-x-hidden">
        <div className="flex flex-col gap-4">
          <h3 className="text-lg font-semibold">🎯 Filters</h3>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium">Prompt</label>
            <Select value={selectedPrompt || undefined} onValueChange={(value) => {
              setSelectedPrompt(value);
              setCurrentTestIdx(0);
            }}>
              <SelectTrigger>
                <SelectValue placeholder="Select prompt" />
              </SelectTrigger>
              <SelectContent>
                {prompts.map((p) => (
                  <SelectItem key={p} value={p}>{p.split(' ')[0]}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium">Model</label>
            <Select value={selectedProvider || undefined} onValueChange={(value) => {
              setSelectedProvider(value);
              setCurrentTestIdx(0);
            }}>
              <SelectTrigger>
                <SelectValue placeholder="Select model" />
              </SelectTrigger>
              <SelectContent>
                {providers.map((p) => (
                  <SelectItem key={p} value={p}>{p}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <Separator />

        <div className="flex flex-col gap-4">
          <h3 className="text-lg font-semibold">📍 Navigation</h3>

          <div className="flex justify-between items-center">
            <span className="text-sm font-medium">Progress</span>
            <Badge variant="secondary">{ratedItems}/{filteredResults.length} rated</Badge>
          </div>
          <Progress value={(ratedItems / filteredResults.length) * 100 || 0} />

          <div className="flex gap-2">
            <Button
              variant="outline"
              className="flex-1"
              onClick={() => setCurrentTestIdx(Math.max(0, currentTestIdx - 1))}
              disabled={currentTestIdx === 0}
            >
              ← Previous
            </Button>
            <Button
              className="flex-1"
              onClick={() => setCurrentTestIdx(Math.min(filteredResults.length - 1, currentTestIdx + 1))}
              disabled={currentTestIdx === filteredResults.length - 1}
            >
              Next →
            </Button>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium">Jump to item</label>
            <Select value={String(currentTestIdx)} onValueChange={(value) => setCurrentTestIdx(parseInt(value))}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {filteredResults.map((r, idx) => (
                  <SelectItem key={idx} value={String(idx)}>
                    #{idx + 1} - {truncateText(r.testCase?.vars?.prompt || 'Q', 40)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <Separator />

        <div className="flex flex-col gap-4">
          <h3 className="text-lg font-semibold">💾 Export</h3>
          <div className="flex flex-col gap-2">
            <Button
              variant="outline"
              className="w-full"
              onClick={() => exportToCSV(data!, annotations)}
            >
              📊 Download CSV
            </Button>
            <Button
              variant="outline"
              className="w-full"
              onClick={() => exportAnnotationsToJSON(annotations)}
            >
              📄 Download Annotations JSON
            </Button>
          </div>

        <Separator />

        <div className="flex flex-col gap-4">
          <h3 className="text-lg font-semibold">📊 Stats</h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-muted-foreground">Rated</p>
              <p className="text-lg font-bold">{ratedItems}/{filteredResults.length}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Average</p>
              <p className="text-lg font-bold">{ratedItems > 0 ? avgRating.toFixed(1) : 'N/A'}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Excellent (5)</p>
              <p className="text-lg font-bold">{allRatings.filter((r) => r === 5).length}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Poor (1)</p>
              <p className="text-lg font-bold">{allRatings.filter((r) => r === 1).length}</p>
            </div>
          </div>
        </div>

        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 p-6 overflow-y-auto">
        <div className="max-w-7xl mx-auto">
          <div className="mb-6">
            <h1 className="text-3xl font-bold">Review Results</h1>
            <p className="text-sm text-muted-foreground">
              Test {currentTestIdx + 1} of {filteredResults.length}
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left Column - Question and Response */}
            <div className="lg:col-span-2 flex flex-col gap-6">
              {/* Question */}
              <Card>
                <CardContent className="">
                  <p className="text-sm">{currentResult.testCase?.vars?.prompt || 'N/A'}</p>
                </CardContent>
              </Card>

              <Separator />

              {/* Model Response */}
              <Card>
                <CardContent className="prose prose-sm max-w-none">
                  <ReactMarkdown>{currentResult.response?.output || 'No output'}</ReactMarkdown>
                </CardContent>
              </Card>

              {/* Test Case Metadata */}
              <div className="flex flex-col gap-4">
                <h4 className="text-lg font-semibold">📌 Test Case Metadata</h4>
                {Object.entries(currentResult.testCase?.vars || {})
                  .filter(([key]) => key !== 'prompt')
                  .map(([key, value]) => (
                    <div key={key}>
                      <p className="text-xs text-muted-foreground font-bold">{key}</p>
                      <p className="text-xs">
                        {typeof value === 'string'
                          ? truncateText(value, 200)
                          : JSON.stringify(value)}
                      </p>
                    </div>
                  ))}
              </div>

              {/* Evaluation Metrics */}
              <div className="flex flex-col gap-4">
                <h4 className="text-lg font-semibold">📊 Evaluation Metrics</h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <Card>
                    <CardContent className="">
                      <p className="text-xs text-muted-foreground">Status</p>
                      <p className="text-sm font-bold">{currentResult.gradingResult?.pass ? '✓ Pass' : '✗ Fail'}</p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent className="">
                      <p className="text-xs text-muted-foreground">Score</p>
                      <p className="text-sm font-bold">{currentResult.gradingResult?.score || 0}</p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent className="">
                      <p className="text-xs text-muted-foreground">Latency</p>
                      <p className="text-sm font-bold">{currentResult.latencyMs}ms</p>
                    </CardContent>
                  </Card>
                </div>
                {currentResult.gradingResult?.reason && (
                  <p className="text-xs">
                    <strong>Reason:</strong> {currentResult.gradingResult.reason}
                  </p>
                )}
              </div>
            </div>

            {/* Right Column - Rating Section */}
            <div className="lg:col-span-1">
              <Card className="sticky top-6 bg-blue-50">
                <CardHeader>
                  <CardTitle>⭐ Your Evaluation</CardTitle>
                </CardHeader>
                <CardContent className="flex flex-col gap-6">
                  <div className="flex flex-col gap-4">
                    <div className="flex justify-between items-center">
                      <span className="text-sm font-medium">Rating</span>
                      <Badge variant="secondary">{ratingLabels[currentAnnotation.rating]}</Badge>
                    </div>
                    <Slider
                      min={0}
                      max={5}
                      step={1}
                      value={[currentAnnotation.rating]}
                      onValueChange={(value) => handleSaveRating(value[0], currentAnnotation.notes)}
                    />
                    <div className="flex justify-between text-xs text-muted-foreground px-1">
                      <span>0</span>
                      <span>1</span>
                      <span>2</span>
                      <span>3</span>
                      <span>4</span>
                      <span>5</span>
                    </div>
                    <p className="text-xs text-muted-foreground">Or press 0-5</p>
                  </div>

                  <Separator />

                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Notes</span>
                    <Textarea
                      ref={textareaRef}
                      placeholder="Add comments..."
                      value={localNotes}
                      onChange={(e) => setLocalNotes(e.currentTarget.value)}
                      rows={8}
                      className="min-h-[200px]"
                    />
                    <p className="text-xs text-muted-foreground">Enter to focus · ⌘↵ to save</p>
                  </div>

                  <div className="flex gap-2">
                    <Button
                      className="flex-1"
                      onClick={() => handleSaveRating(currentAnnotation.rating, localNotes)}
                    >
                      💾 Save
                    </Button>
                    <Button
                      variant="outline"
                      className="flex-1"
                      onClick={handleSaveAndNext}
                    >
                      Next
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
