// review-app-mantine/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import {
  AppShell,
  Box,
  Button,
  Grid,
  Group,
  Progress,
  Select,
  SimpleGrid,
  Slider,
  Stack,
  Text,
  Textarea,
  Title,
  Badge,
  Divider,
  Alert,
  Loader,
  Center,
  ScrollArea,
} from '@mantine/core';
import ReactMarkdown from 'react-markdown';
import {
  loadPromptfooResults,
  loadAnnotations,
  saveAnnotations,
  getAnnotation,
  setAnnotation,
  truncateText,
} from './utils/data';
import type { PromptfooResult, AnnotationsStore } from './types';
import './App.css';

function App() {
  const [data, setData] = useState<PromptfooResult | null>(null);
  const [annotations, setAnnotations] = useState<AnnotationsStore>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [selectedPrompt, setSelectedPrompt] = useState<string | null>(null);
  const [selectedProvider, setSelectedProvider] = useState<string | null>(null);
  const [currentTestIdx, setCurrentTestIdx] = useState(0);
  const [localNotes, setLocalNotes] = useState('');

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Load data on mount
  useEffect(() => {
    const loadData = async () => {
      try {
        const promptfooData = await loadPromptfooResults();
        if (!promptfooData) {
          setError('No evaluation results found. Run promptfoo first.');
          setLoading(false);
          return;
        }

        setData(promptfooData);

        // Load annotations
        const annots = await loadAnnotations();
        setAnnotations(annots);

        // Set initial selections
        const prompts = Array.from(
          new Set(
            promptfooData.results.results.map((r) => r.prompt?.label || 'unknown')
          )
        ).sort();
        const providers = Array.from(
          new Set(
            promptfooData.results.results.map((r) => r.provider?.label || 'unknown')
          )
        ).sort();

        if (prompts.length > 0) setSelectedPrompt(prompts[0]);
        if (providers.length > 0) setSelectedProvider(providers[0]);
      } catch (err) {
        setError(`Failed to load data: ${err}`);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Get unique prompts and providers
  const prompts = data
    ? Array.from(
        new Set(data.results.results.map((r) => r.prompt?.label || 'unknown'))
      ).sort()
    : [];
  const providers = data
    ? Array.from(
        new Set(data.results.results.map((r) => r.provider?.label || 'unknown'))
      ).sort()
    : [];

  // Filter results
  const filteredResults =
    data && selectedPrompt && selectedProvider
      ? data.results.results.filter(
          (r) =>
            r.prompt?.label === selectedPrompt &&
            r.provider?.label === selectedProvider
        )
      : [];

  const currentResult = filteredResults[currentTestIdx];

  // Get current annotation
  const currentAnnotation = currentResult
    ? getAnnotation(
        annotations,
        data!.evalId,
        currentResult.testIdx,
        selectedPrompt!,
        selectedProvider!
      )
    : { rating: 0, notes: '' };

  // Sync localNotes when currentAnnotation changes
  useEffect(() => {
    setLocalNotes(currentAnnotation.notes);
  }, [currentAnnotation.notes, currentTestIdx]);

  // Handle keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const targetElement = event.target as HTMLElement;

      // Number keys 0-5 to set rating
      if (event.key >= '0' && event.key <= '5') {
        // Only handle if not typing in an input/textarea
        if (
          targetElement.tagName !== 'INPUT' &&
          targetElement.tagName !== 'TEXTAREA'
        ) {
          event.preventDefault();
          const newRating = parseInt(event.key);
          handleSaveRating(newRating, currentAnnotation.notes);
        }
      }

      // Enter to focus textarea
      if (event.key === 'Enter' && !event.metaKey && !event.ctrlKey) {
        if (
          targetElement.tagName !== 'TEXTAREA' &&
          targetElement.tagName !== 'INPUT'
        ) {
          event.preventDefault();
          textareaRef.current?.focus();
        }
      }

      // Cmd+Enter (or Ctrl+Enter) to save and move to next
      if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
        if (targetElement.tagName === 'TEXTAREA') {
          event.preventDefault();
          handleSaveAndNext();
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentAnnotation, currentResult, selectedPrompt, selectedProvider, currentTestIdx, filteredResults, data, annotations]);

  const handleSaveRating = (rating: number, notes: string) => {
    if (!currentResult || !selectedPrompt || !selectedProvider) return;

    const updated = setAnnotation(
      annotations,
      data!.evalId,
      currentResult.testIdx,
      selectedPrompt,
      selectedProvider,
      rating,
      notes
    );
    setAnnotations(updated);
    saveAnnotations(updated);
  };

  const handleSaveAndNext = () => {
    if (!currentResult || !selectedPrompt || !selectedProvider) return;

    handleSaveRating(currentAnnotation.rating, localNotes);

    if (currentTestIdx < filteredResults.length - 1) {
      setCurrentTestIdx(currentTestIdx + 1);
    }
  };

  const ratingLabels: Record<number, string> = {
    0: '⏳ Not rated',
    1: '❌ Poor',
    2: '⚠️ Needs improvement',
    3: '✓ Acceptable',
    4: '✓✓ Good',
    5: '✓✓✓ Excellent',
  };

  // Calculate stats
  const allRatings = filteredResults.map((r) =>
    getAnnotation(
      annotations,
      data!.evalId,
      r.testIdx,
      selectedPrompt!,
      selectedProvider!
    ).rating
  );
  const ratedItems = allRatings.filter((r) => r > 0).length;
  const avgRating = ratedItems > 0 ? allRatings.reduce((a, b) => a + b, 0) / ratedItems : 0;

  if (loading) {
    return (
      <Center style={{ height: '100vh' }}>
        <Loader />
      </Center>
    );
  }

  if (error) {
    return (
      <Center style={{ height: '100vh' }}>
        <Alert color="red" title="Error">
          {error}
        </Alert>
      </Center>
    );
  }

  if (!currentResult || !data) {
    return (
      <Center style={{ height: '100vh' }}>
        <Alert color="yellow" title="No Results">
          No results found for this combination
        </Alert>
      </Center>
    );
  }

  return (
    <AppShell
      navbar={{
        width: 280,
        breakpoint: 'sm',
        collapsed: { mobile: true },
      }}
      padding="xs"
    >
      <AppShell.Navbar p="md">
        <Stack h="100%">
          <Title order={3}>🎯 Filters</Title>

          <Select
            label="Prompt"
            placeholder="Select prompt"
            data={prompts}
            value={selectedPrompt}
            onChange={(value) => {
              setSelectedPrompt(value);
              setCurrentTestIdx(0);
            }}
          />

          <Select
            label="Model"
            placeholder="Select model"
            data={providers}
            value={selectedProvider}
            onChange={(value) => {
              setSelectedProvider(value);
              setCurrentTestIdx(0);
            }}
          />

          <Divider />

          <Title order={3}>📍 Navigation</Title>

          <Group justify="space-between">
            <Text size="sm" fw={500}>
              Progress
            </Text>
            <Badge variant="light" size="lg">
              {ratedItems}/{filteredResults.length} rated
            </Badge>
          </Group>
          <Progress
            value={
              (ratedItems / filteredResults.length) * 100 || 0
            }
          />

          <Group grow>
            <Button
              variant="default"
              onClick={() =>
                setCurrentTestIdx(Math.max(0, currentTestIdx - 1))
              }
              disabled={currentTestIdx === 0}
            >
              ← Previous
            </Button>
            <Button
              onClick={() =>
                setCurrentTestIdx(
                  Math.min(filteredResults.length - 1, currentTestIdx + 1)
                )
              }
              disabled={currentTestIdx === filteredResults.length - 1}
            >
              Next →
            </Button>
          </Group>

          <Select
            label="Jump to item"
            placeholder="Select item"
            data={filteredResults.map((r, idx) => ({
              value: String(idx),
              label: `#${idx + 1} - ${truncateText(
                r.testCase?.vars?.prompt || 'Q',
                40
              )}`,
            }))}
            value={String(currentTestIdx)}
            onChange={(value) => setCurrentTestIdx(parseInt(value || '0'))}
          />

          <Divider />

          <Title order={3}>📊 Stats</Title>
          <SimpleGrid cols={2}>
            <Box>
              <Text size="xs" c="dimmed">
                Rated
              </Text>
              <Text size="lg" fw={700}>
                {ratedItems}/{filteredResults.length}
              </Text>
            </Box>
            <Box>
              <Text size="xs" c="dimmed">
                Average
              </Text>
              <Text size="lg" fw={700}>
                {ratedItems > 0 ? avgRating.toFixed(1) : 'N/A'}
              </Text>
            </Box>
            <Box>
              <Text size="xs" c="dimmed">
                Excellent (5)
              </Text>
              <Text size="lg" fw={700}>
                {allRatings.filter((r) => r === 5).length}
              </Text>
            </Box>
            <Box>
              <Text size="xs" c="dimmed">
                Poor (1)
              </Text>
              <Text size="lg" fw={700}>
                {allRatings.filter((r) => r === 1).length}
              </Text>
            </Box>
          </SimpleGrid>
        </Stack>
      </AppShell.Navbar>

      <AppShell.Main>
        <Stack>
          <Title>Review Results</Title>
          <Text c="dimmed" size="sm">
            Test {currentTestIdx + 1} of {filteredResults.length}
          </Text>
        </Stack>

        <Grid gutter="md" mt="md">
          <Grid.Col span={{ base: 12, lg: 8 }}>
            <Stack>
              {/* Question */}
              <Box
                p="md"
                style={{
                  backgroundColor: 'var(--mantine-color-gray-0)',
                  borderRadius: 'var(--mantine-radius-md)',
                  border: '1px solid var(--mantine-color-gray-2)',
                }}
              >
                <Text size="sm">{currentResult.testCase?.vars?.prompt || 'N/A'}</Text>
              </Box>

              <Divider />

              {/* Model Response */}
              <ScrollArea>
                <Box
                  p="md"
                  style={{
                    backgroundColor: 'var(--mantine-color-gray-0)',
                    borderRadius: 'var(--mantine-radius-md)',
                    border: '1px solid var(--mantine-color-gray-2)',
                    minHeight: '200px',
                    fontSize: '0.9rem',
                    lineHeight: 1.5,
                  }}
                >
                  <ReactMarkdown>{currentResult.response?.output || 'No output'}</ReactMarkdown>
                </Box>
              </ScrollArea>

              {/* Evaluation Metrics */}
              <Stack gap="xs">
                <Title order={4}>📊 Evaluation Metrics</Title>
                <SimpleGrid cols={{ base: 1, sm: 3 }}>
                  <Box
                    p="md"
                    style={{
                      backgroundColor: 'var(--mantine-color-gray-0)',
                      borderRadius: 'var(--mantine-radius-md)',
                      border: '1px solid var(--mantine-color-gray-2)',
                    }}
                  >
                    <Text size="xs" c="dimmed">
                      Status
                    </Text>
                    <Text size="sm" fw={700}>
                      {currentResult.gradingResult?.pass ? '✓ Pass' : '✗ Fail'}
                    </Text>
                  </Box>
                  <Box
                    p="md"
                    style={{
                      backgroundColor: 'var(--mantine-color-gray-0)',
                      borderRadius: 'var(--mantine-radius-md)',
                      border: '1px solid var(--mantine-color-gray-2)',
                    }}
                  >
                    <Text size="xs" c="dimmed">
                      Score
                    </Text>
                    <Text size="sm" fw={700}>{currentResult.gradingResult?.score || 0}</Text>
                  </Box>
                  <Box
                    p="md"
                    style={{
                      backgroundColor: 'var(--mantine-color-gray-0)',
                      borderRadius: 'var(--mantine-radius-md)',
                      border: '1px solid var(--mantine-color-gray-2)',
                    }}
                  >
                    <Text size="xs" c="dimmed">
                      Latency
                    </Text>
                    <Text size="sm" fw={700}>{currentResult.latencyMs}ms</Text>
                  </Box>
                </SimpleGrid>
                {currentResult.gradingResult?.reason && (
                  <Text size="xs">
                    <strong>Reason:</strong> {currentResult.gradingResult.reason}
                  </Text>
                )}
              </Stack>

              {/* Test Case Metadata */}
              <Stack gap="xs">
                <Title order={4}>📌 Test Case Metadata</Title>
                {Object.entries(currentResult.testCase?.vars || {})
                  .filter(
                    ([key]) =>
                      ![
                        'prompt',
                        'Source',
                        'Bot current capability expectations; assuming we have Bot Guide correct, the Bot...',
                        'How good of a test for the Bot is this question?',
                        'Applies to:',
                        'JP Answer',
                        'Notes',
                      ].includes(key) || key === 'prompt'
                  )
                  .slice(0, 4)
                  .map(([key, value]) => (
                    <Box key={key}>
                      <Text size="xs" c="dimmed" fw={700}>
                        {key}
                      </Text>
                      <Text size="xs">
                        {typeof value === 'string'
                          ? truncateText(value, 200)
                          : JSON.stringify(value)}
                      </Text>
                    </Box>
                  ))}
              </Stack>
            </Stack>
          </Grid.Col>

          <Grid.Col span={{ base: 12, lg: 4 }}>
            {/* Rating Section */}
            <Box
              p="md"
              style={{
                backgroundColor: 'var(--mantine-color-blue-0)',
                borderRadius: 'var(--mantine-radius-md)',
                border: '1px solid var(--mantine-color-blue-2)',
                position: 'sticky',
                top: 'var(--mantine-spacing-sm)',
              }}
            >
              <Stack>
                <Title order={4}>⭐ Your Evaluation</Title>

                <Stack gap="lg">
                  <Group justify="space-between">
                    <Text size="sm" fw={500}>Rating</Text>
                    <Badge size="sm">{ratingLabels[currentAnnotation.rating]}</Badge>
                  </Group>
                  <Slider
                    min={0}
                    max={5}
                    step={1}
                    value={currentAnnotation.rating}
                    onChange={(value) =>
                      handleSaveRating(value, currentAnnotation.notes)
                    }
                    marks={[
                      { value: 0, label: '0' },
                      { value: 1, label: '1' },
                      { value: 2, label: '2' },
                      { value: 3, label: '3' },
                      { value: 4, label: '4' },
                      { value: 5, label: '5' },
                    ]}
                  />
                  <Text size="xs" c="dimmed">
                    Or press 0-5
                  </Text>
                </Stack>

                <Divider />

                <Stack gap="xs">
                  <Text size="sm" fw={500}>
                    Notes
                  </Text>
                  <Textarea
                    ref={textareaRef}
                    placeholder="Add comments..."
                    value={localNotes}
                    onChange={(e) => setLocalNotes(e.currentTarget.value)}
                    rows={8}
                    size="sm"
                    style={{ minHeight: '200px' }}
                  />
                  <Text size="xs" c="dimmed">
                    Enter to focus · ⌘↵ to save
                  </Text>
                </Stack>

                <Group grow>
                  <Button
                    size="sm"
                    onClick={() => {
                      handleSaveRating(currentAnnotation.rating, localNotes);
                    }}
                    fullWidth
                  >
                    💾 Save
                  </Button>
                  <Button
                    size="sm"
                    variant="default"
                    onClick={handleSaveAndNext}
                    fullWidth
                  >
                    Next
                  </Button>
                </Group>
              </Stack>
            </Box>
          </Grid.Col>
        </Grid>
      </AppShell.Main>
    </AppShell>
  );
}

export default App;

// review-app/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  interface TestResult {
    testIdx: number;
    prompt: { label: string };
    provider: { label: string };
    testCase: { vars: Record<string, string> };
    response: { output: string };
    gradingResult: { pass: boolean; score: number; reason: string };
    latencyMs: number;
  }

  interface Annotation {
    rating: number;
    notes: string;
  }

  interface AnnotationsData {
    [evalId: string]: {
      [testIdx: string]: {
        [promptLabel: string]: {
          [providerLabel: string]: Annotation;
        };
      };
    };
  }

  let results: TestResult[] = [];
  let allResults: TestResult[] = [];
  let annotations: AnnotationsData = {};
  let evalId = '';
  let selectedPrompt = '';
  let selectedProvider = '';
  let currentTestIdx = 0;
  let loading = true;
  let error = '';

  let rating = 0;
  let notes = '';
  let notesTextarea: HTMLTextAreaElement;

  onMount(async () => {
    try {
      const [resultsRes, annotationsRes] = await Promise.all([
        fetch('/api/results'),
        fetch('/api/annotations'),
      ]);

      if (!resultsRes.ok) throw new Error('Failed to load results');
      if (!annotationsRes.ok) throw new Error('Failed to load annotations');

      const resultsData = await resultsRes.json();
      const annotationsData = await annotationsRes.json();

      allResults = resultsData.results || [];
      annotations = annotationsData;
      evalId = resultsData.evalId || '';

      // Get unique prompts and providers
      const uniquePrompts = new Set<string>();
      const uniqueProviders = new Set<string>();

      allResults.forEach((r) => {
        uniquePrompts.add(r.prompt?.label || 'unknown');
        uniqueProviders.add(r.provider?.label || 'unknown');
      });

      selectedPrompt = Array.from(uniquePrompts)[0] || '';
      selectedProvider = Array.from(uniqueProviders)[0] || '';

      filterResults();
      loading = false;
    } catch (e) {
      error = String(e);
      loading = false;
    }
  });

  function filterResults() {
    results = allResults.filter(
      (r) =>
        r.prompt?.label === selectedPrompt &&
        r.provider?.label === selectedProvider
    );
    currentTestIdx = 0;
    loadCurrentResult();
  }

  function loadCurrentResult() {
    if (results.length === 0) return;

    const result = results[currentTestIdx];
    const testIdx = result.testIdx;

    const annotation = annotations[evalId]?.[testIdx]?.[selectedPrompt]?.[
      selectedProvider
    ] || { rating: 0, notes: '' };

    rating = annotation.rating || 0;
    notes = annotation.notes || '';
  }

  function truncate(text: string, maxLength = 150): string {
    if (!text) return '';
    return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
  }

  function getUniquePrompts(): string[] {
    const unique = new Set<string>();
    allResults.forEach((r) => unique.add(r.prompt?.label || 'unknown'));
    return Array.from(unique).sort();
  }

  function getUniqueProviders(): string[] {
    const unique = new Set<string>();
    allResults.forEach((r) => unique.add(r.provider?.label || 'unknown'));
    return Array.from(unique).sort();
  }

  function setRating(newRating: number) {
    rating = newRating;
  }

  async function saveAndNext() {
    const result = results[currentTestIdx];
    const testIdx = result.testIdx;

    if (!annotations[evalId]) annotations[evalId] = {};
    if (!annotations[evalId][testIdx]) annotations[evalId][testIdx] = {};
    if (!annotations[evalId][testIdx][selectedPrompt]) {
      annotations[evalId][testIdx][selectedPrompt] = {};
    }

    annotations[evalId][testIdx][selectedPrompt][selectedProvider] = {
      rating,
      notes,
    };

    try {
      const res = await fetch('/api/annotations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(annotations),
      });

      if (!res.ok) throw new Error('Failed to save');

      if (currentTestIdx < results.length - 1) {
        currentTestIdx++;
        loadCurrentResult();
      }
    } catch (e) {
      error = String(e);
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    // Skip if we're typing in the textarea
    if (document.activeElement === notesTextarea) {
      // Cmd+Enter to save
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        saveAndNext();
      }
      return;
    }

    // 0-5 to set rating
    if (/^[0-5]$/.test(e.key)) {
      setRating(parseInt(e.key, 10));
      return;
    }

    // Enter to focus notes
    if (e.key === 'Enter') {
      e.preventDefault();
      notesTextarea?.focus();
    }
  }

  const ratedCount = results.filter((r) => {
    const annotation =
      annotations[evalId]?.[r.testIdx]?.[selectedPrompt]?.[selectedProvider] ||
      {};
    return (annotation.rating || 0) > 0;
  }).length;

  const allRatings = results.map((r) => {
    const annotation =
      annotations[evalId]?.[r.testIdx]?.[selectedPrompt]?.[selectedProvider] ||
      {};
    return annotation.rating || 0;
  });

  const avgRating =
    allRatings.filter((r) => r > 0).length > 0
      ? allRatings.reduce((a, b) => a + b, 0) /
        allRatings.filter((r) => r > 0).length
      : 0;

  const ratingsMap = {
    0: '⏳ Not rated',
    1: '❌ Poor',
    2: '⚠️ Needs improvement',
    3: '✓ Acceptable',
    4: '✓✓ Good',
    5: '✓✓✓ Excellent',
  };

  $: if (results.length > 0) {
    loadCurrentResult();
  }
</script>

<svelte:window on:keydown={handleKeyDown} />

<style>
  :global(body) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
      'Helvetica Neue', Arial, sans-serif;
    background: #f5f5f5;
    margin: 0;
    padding: 0;
  }

  .container {
    display: grid;
    grid-template-columns: 300px 1fr;
    gap: 0;
    height: 100vh;
  }

  .sidebar {
    background: #fff;
    border-right: 1px solid #e0e0e0;
    padding: 24px;
    overflow-y: auto;
  }

  .main {
    display: flex;
    flex-direction: column;
    padding: 24px;
    overflow: hidden;
  }

  .content-wrapper {
    display: grid;
    grid-template-columns: 1fr 350px;
    gap: 24px;
    flex: 1;
    overflow: hidden;
    margin-bottom: 24px;
  }

  .left-panel {
    display: flex;
    flex-direction: column;
    gap: 12px;
    overflow: hidden;
  }

  .header {
    font-size: 20px;
    font-weight: 600;
    margin: 0 0 16px 0;
  }

  .section-header {
    font-size: 14px;
    font-weight: 600;
    text-transform: uppercase;
    color: #666;
    margin: 16px 0 12px 0;
    border-bottom: 1px solid #e0e0e0;
    padding-bottom: 8px;
  }

  .select-group {
    margin-bottom: 16px;
  }

  label {
    display: block;
    font-size: 12px;
    font-weight: 500;
    margin-bottom: 6px;
    color: #333;
  }

  select {
    width: 100%;
    padding: 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
  }

  .navigation {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    margin: 16px 0;
  }

  button {
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: #fff;
    cursor: pointer;
    font-size: 13px;
    transition: all 0.2s;
  }

  button:hover {
    background: #f0f0f0;
    border-color: #999;
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .metric {
    margin: 8px 0;
    font-size: 13px;
    color: #666;
  }

  .metric-value {
    font-weight: 600;
    color: #333;
  }

  .title {
    font-size: 24px;
    font-weight: 600;
    margin: 0 0 4px 0;
  }

  .caption {
    font-size: 13px;
    color: #999;
    margin-bottom: 12px;
  }

  .question {
    background: #f9f9f9;
    padding: 12px;
    border-radius: 4px;
    margin-bottom: 12px;
    font-size: 13px;
    line-height: 1.5;
    border-left: 3px solid #2196f3;
    flex-shrink: 0;
  }

  .response {
    background: #fff;
    padding: 16px;
    border-radius: 4px;
    margin-bottom: 12px;
    font-size: 14px;
    line-height: 1.6;
    border: 1px solid #e0e0e0;
    overflow-y: auto;
    flex: 1;
  }

  .metrics-section {
    background: #f9f9f9;
    padding: 12px;
    border-radius: 4px;
    font-size: 12px;
    flex-shrink: 0;
  }

  .metrics-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
    margin: 8px 0;
  }

  .metric-item {
    background: #fff;
    padding: 8px;
    border-radius: 3px;
    border: 1px solid #e0e0e0;
    text-align: center;
  }

  .rating-section {
    background: #fff;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
    padding: 16px;
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  .subheader {
    font-size: 16px;
    font-weight: 600;
    margin: 0 0 12px 0;
  }

  .rating-control {
    margin-bottom: 16px;
    flex-shrink: 0;
  }

  .rating-label {
    font-size: 14px;
    font-weight: 500;
    margin-bottom: 8px;
  }

  .rating-slider {
    width: 100%;
    height: 6px;
    border-radius: 3px;
    background: #ddd;
    outline: none;
    -webkit-appearance: none;
  }

  .rating-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: #2196f3;
    cursor: pointer;
  }

  .rating-slider::-moz-range-thumb {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: #2196f3;
    cursor: pointer;
    border: none;
  }

  .rating-display {
    font-size: 14px;
    font-weight: 600;
    color: #333;
    margin-top: 8px;
  }

  .notes-section {
    margin-top: 16px;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .notes-label {
    font-size: 14px;
    font-weight: 500;
    margin-bottom: 8px;
    flex-shrink: 0;
  }

  textarea {
    flex: 1;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
      'Helvetica Neue', Arial, sans-serif;
    font-size: 13px;
    resize: none;
    min-height: 0;
  }

  .button-group {
    display: grid;
    grid-template-columns: 1fr;
    gap: 8px;
    margin-top: 16px;
    flex-shrink: 0;
  }

  .save-button {
    background: #2196f3;
    color: white;
    border: none;
    padding: 10px;
    font-weight: 500;
    width: 100%;
  }

  .save-button:hover {
    background: #1976d2;
  }

  .loading,
  .error-message {
    padding: 24px;
    text-align: center;
  }

  .error-message {
    color: #d32f2f;
  }

  .stats-section {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    flex-shrink: 0;
    border-top: 1px solid #e0e0e0;
    padding-top: 16px;
  }

  .stat-item {
    background: #fff;
    padding: 12px;
    border-radius: 4px;
    border: 1px solid #e0e0e0;
    text-align: center;
  }

  .stat-label {
    font-size: 11px;
    color: #999;
    text-transform: uppercase;
    font-weight: 500;
  }

  .stat-value {
    font-size: 20px;
    font-weight: 600;
    margin-top: 6px;
  }

  .keyboard-hint {
    font-size: 11px;
    color: #999;
    margin-top: 8px;
    font-style: italic;
  }

  input[type='range'] {
    cursor: pointer;
  }
</style>

{#if loading}
  <div class="loading">Loading...</div>
{:else if error}
  <div class="error-message">Error: {error}</div>
{:else if results.length === 0}
  <div class="error-message">No results found for this combination</div>
{:else}
  <div class="container">
    <div class="sidebar">
      <h2 class="header">🎯 Filters</h2>

      <div class="select-group">
        <label for="prompt-select">Prompt:</label>
        <select
          id="prompt-select"
          bind:value={selectedPrompt}
          on:change={filterResults}
        >
          {#each getUniquePrompts() as p}
            <option value={p}>{p}</option>
          {/each}
        </select>
      </div>

      <div class="select-group">
        <label for="provider-select">Model:</label>
        <select
          id="provider-select"
          bind:value={selectedProvider}
          on:change={filterResults}
        >
          {#each getUniqueProviders() as pr}
            <option value={pr}>{pr}</option>
          {/each}
        </select>
      </div>

      <div class="section-header">📍 Navigation</div>

      <div class="metric">
        <div class="metric-value">Progress</div>
        <div>{ratedCount}/{results.length} rated</div>
      </div>

      <div class="navigation">
        <button
          disabled={currentTestIdx === 0}
          on:click={() => {
            currentTestIdx--;
          }}
        >
          ← Previous
        </button>
        <button
          disabled={currentTestIdx === results.length - 1}
          on:click={() => {
            currentTestIdx++;
          }}
        >
          Next →
        </button>
      </div>

      {#if results.length > 0}
        <div class="select-group">
          <label for="jump-select">Jump to item:</label>
          <select
            id="jump-select"
            bind:value={currentTestIdx}
            on:change={() => {
              currentTestIdx = parseInt(currentTestIdx);
            }}
          >
            {#each results as result, idx}
              <option value={idx}>
                #{idx + 1} - {truncate(
                  result.testCase?.vars?.prompt || 'Q',
                  40
                )}
              </option>
            {/each}
          </select>
        </div>
      {/if}

      <div class="section-header">📊 Keyboard Shortcuts</div>
      <div class="keyboard-hint">
        <strong>0-5</strong>: Set rating<br />
        <strong>Enter</strong>: Focus notes<br />
        <strong>Cmd+Enter</strong>: Save & next
      </div>
    </div>

    <div class="main">
      {#if results.length > 0}
        <div>
          <div class="title">Review Results</div>
          <div class="caption">
            Test {currentTestIdx + 1} of {results.length}
          </div>
        </div>

        <div class="content-wrapper">
          <div class="left-panel">
            <div class="question">
              <strong>Question:</strong><br />
              {truncate(results[currentTestIdx].testCase?.vars?.prompt, 300)}
            </div>

            <div class="response">
              <strong>Model Response:</strong><br />
              {results[currentTestIdx].response?.output || 'No output'}
            </div>

            <div class="metrics-section">
              <strong>📊 Evaluation Metrics</strong>
              <div class="metrics-row">
                <div class="metric-item">
                  <div class="stat-label">Status</div>
                  <div class="stat-value">
                    {results[currentTestIdx].gradingResult?.pass ? '✓' : '✗'}
                  </div>
                </div>
                <div class="metric-item">
                  <div class="stat-label">Score</div>
                  <div class="stat-value">
                    {results[currentTestIdx].gradingResult?.score || 0}
                  </div>
                </div>
                <div class="metric-item">
                  <div class="stat-label">Latency</div>
                  <div class="stat-value">
                    {results[currentTestIdx].latencyMs}ms
                  </div>
                </div>
              </div>
              {#if results[currentTestIdx].gradingResult?.reason}
                <div style="margin-top: 8px; font-size: 12px;">
                  <strong>Reason:</strong> {results[currentTestIdx].gradingResult
                    ?.reason}
                </div>
              {/if}
            </div>
          </div>

          <div class="rating-section">
            <div class="subheader">⭐ Your Evaluation</div>

            <div class="rating-control">
              <label for="rating-slider" class="rating-label">
                Rating:
              </label>
              <input
                id="rating-slider"
                type="range"
                class="rating-slider"
                min="0"
                max="5"
                bind:value={rating}
                on:change={() => {
                  rating = parseInt(rating);
                }}
              />
              <div class="rating-display">
                {ratingsMap[rating]}
              </div>
            </div>

            <div class="notes-section">
              <label for="notes-textarea" class="notes-label">Notes:</label>
              <textarea
                id="notes-textarea"
                bind:value={notes}
                bind:this={notesTextarea}
                placeholder="Add comments or observations..."
              />
            </div>

            <div class="button-group">
              <button class="save-button" on:click={saveAndNext}>
                💾 Save & Continue
              </button>
            </div>
          </div>
        </div>

        <div class="stats-section">
          <div class="stat-item">
            <div class="stat-label">Rated</div>
            <div class="stat-value">{ratedCount}/{results.length}</div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Avg Rating</div>
            <div class="stat-value">
              {avgRating > 0 ? avgRating.toFixed(1) : 'N/A'}
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Excellent (5)</div>
            <div class="stat-value">
              {allRatings.filter((r) => r === 5).length}
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Poor (1)</div>
            <div class="stat-value">
              {allRatings.filter((r) => r === 1).length}
            </div>
          </div>
        </div>
      {/if}
    </div>
  </div>
{/if}
